import type { Job } from 'bullmq';
import type { PrismaClient } from '@lead-saas/database';
import type { Redis } from 'ioredis';
import { decryptCredential } from '../../common/credential-cipher.js';
import type { MessagingProvider } from './provider.js';
export class MessageProcessor{
 constructor(private readonly db:PrismaClient,private readonly redis:Redis,private readonly provider:MessagingProvider,private readonly encryptionKey:string){}
 async process(job:Job<{messageId:string}>):Promise<{messageId:string}>{const message=await this.db.message.findUnique({where:{id:job.data.messageId},include:{conversation:{include:{lead:true}}}});if(!message||message.direction!=='OUTBOUND')throw new Error('Outbound message not found');if(message.status==='SENT'||message.status==='DELIVERED')return{messageId:message.id};
  try{await this.db.message.update({where:{id:message.id},data:{status:'PENDING'}});const conversation=message.conversation;if(conversation.channel!=='MESSENGER')throw new Error('Unsupported provider channel');const lastInbound=await this.db.message.findFirst({where:{organizationId:message.organizationId,conversationId:conversation.id,direction:'INBOUND'},orderBy:{createdAt:'desc'}});if(!lastInbound||lastInbound.createdAt.getTime()<Date.now()-86_400_000)throw new Error('Messenger standard reply window has expired');const pageId=conversation.lead?.externalPageId;if(!pageId)throw new Error('Conversation has no provider Page');const page=await this.db.metaPage.findFirst({where:{organizationId:message.organizationId,externalPageId:pageId,status:'ACTIVE'}});if(!page?.accessTokenReference)throw new Error('Page credential unavailable');const result=await this.provider.sendText(conversation.externalConversationId,message.content,decryptCredential(page.accessTokenReference,this.encryptionKey));const now=new Date();const periodStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const periodEnd=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));await this.db.$transaction([this.db.message.update({where:{id:message.id},data:{status:'SENT',externalMessageId:result.externalMessageId}}),...(conversation.leadId?[this.db.activity.create({data:{organizationId:message.organizationId,leadId:conversation.leadId,actorUserId:message.senderExternalId,type:'MESSAGE_SENT',metadataJson:{messageId:message.id}}})]:[]),this.db.conversation.update({where:{id:conversation.id},data:{lastMessageAt:new Date()}}),this.db.usageCounter.upsert({where:{organizationId_metric_periodStart:{organizationId:message.organizationId,metric:'messages',periodStart}},create:{organizationId:message.organizationId,metric:'messages',periodStart,periodEnd,value:1},update:{value:{increment:1}}})]);await this.redis.publish(`realtime:organization:${message.organizationId}`,JSON.stringify({event:'message.updated',data:{messageId:message.id,status:'SENT'}}));return{messageId:message.id};}catch(error){await this.db.message.update({where:{id:message.id},data:{status:'FAILED',metadataJson:{safeError:error instanceof Error?error.message:'Provider send failed'}}});await this.redis.publish(`realtime:organization:${message.organizationId}`,JSON.stringify({event:'message.updated',data:{messageId:message.id,status:'FAILED'}}));throw error;}}
}
