import { BadRequestException, Injectable, NotFoundException, OnModuleDestroy } from '@nestjs/common';
import { Queue } from 'bullmq';
import { Redis } from 'ioredis';
import { ConfigService } from '@nestjs/config';
import { DatabaseService } from '../common/database.module.js';
import type { AuthContext } from '../common/auth-context.js';
import type { UpdateConversationDto } from './conversations.dto.js';
import { PlanLimitsService } from '../billing/plan-limits.service.js';
@Injectable()
export class ConversationsService implements OnModuleDestroy {
  private readonly connection:Redis; private readonly queue:Queue;
  constructor(private readonly db:DatabaseService,config:ConfigService,private readonly limits:PlanLimitsService){this.connection=new Redis(config.getOrThrow('REDIS_URL'),{maxRetriesPerRequest:null});this.queue=new Queue('provider-messaging',{connection:this.connection,defaultJobOptions:{attempts:5,backoff:{type:'exponential',delay:2000},removeOnComplete:1000,removeOnFail:5000}});}
  async list(auth:AuthContext,filter:'all'|'unread'|'mine'='all',cursor?:string){const conversations=await this.db.conversation.findMany({where:{organizationId:auth.organizationId,...(auth.role==='AGENT'||filter==='mine'?{assignedUserId:auth.userId}:{})},take:26,...(cursor?{cursor:{id:cursor},skip:1}:{}),orderBy:[{lastMessageAt:'desc'},{id:'desc'}],include:{lead:{select:{id:true,name:true,email:true,phone:true}},assignedUser:{select:{id:true,name:true}},messages:{take:1,orderBy:{createdAt:'desc'}},reads:{where:{userId:auth.userId},take:1}}});const rows=conversations.map((c)=>({...c,unread:c.messages[0]?.direction==='INBOUND'&&(!c.reads[0]||c.messages[0].createdAt>c.reads[0].lastReadAt)})).filter((c)=>filter!=='unread'||c.unread);const data=rows.slice(0,25);return{data,nextCursor:rows.length>25?data.at(-1)?.id??null:null};}
  async get(auth:AuthContext,id:string){const value=await this.db.conversation.findFirst({where:{id,organizationId:auth.organizationId,...(auth.role==='AGENT'?{assignedUserId:auth.userId}:{})},include:{lead:true,assignedUser:{select:{id:true,name:true}}}});if(!value)throw new NotFoundException('Conversation was not found.');return value;}
  async messages(auth:AuthContext,id:string,cursor?:string){await this.get(auth,id);const rows=await this.db.message.findMany({where:{organizationId:auth.organizationId,conversationId:id},take:51,...(cursor?{cursor:{id:cursor},skip:1}:{}),orderBy:[{createdAt:'desc'},{id:'desc'}]});const data=rows.slice(0,50);return{data,nextCursor:rows.length>50?data.at(-1)?.id??null:null};}
  async send(auth:AuthContext,id:string,content:string){const conversation=await this.get(auth,id);if(conversation.channel!=='MESSENGER')throw new BadRequestException('Sending is not supported for this channel.');if(conversation.status!=='OPEN')throw new BadRequestException('Conversation is closed.');await this.limits.assertMessages(auth.organizationId);const message=await this.db.message.create({data:{organizationId:auth.organizationId,conversationId:id,direction:'OUTBOUND',senderType:'USER',senderExternalId:auth.userId,content,status:'PENDING'}});await this.queue.add('send-message',{messageId:message.id},{jobId:message.id});return message;}
  async retry(auth:AuthContext,id:string,messageId:string){await this.get(auth,id);const message=await this.db.message.findFirst({where:{id:messageId,conversationId:id,organizationId:auth.organizationId,direction:'OUTBOUND'}});if(!message)throw new NotFoundException('Message was not found.');if(message.status!=='FAILED')throw new BadRequestException('Only failed messages can be retried.');await this.limits.assertMessages(auth.organizationId);const pending=await this.db.message.update({where:{id:message.id},data:{status:'PENDING',metadataJson:{}}});await this.queue.add('send-message',{messageId:message.id},{jobId:`${message.id}-${Date.now()}`});return pending;}
  async read(auth:AuthContext,id:string){await this.get(auth,id);await this.db.conversationRead.upsert({where:{conversationId_userId:{conversationId:id,userId:auth.userId}},create:{conversationId:id,userId:auth.userId,organizationId:auth.organizationId},update:{lastReadAt:new Date()}});return{success:true};}
  async update(auth:AuthContext,id:string,input:UpdateConversationDto){await this.get(auth,id);if(input.assignedUserId){const member=await this.db.organizationUser.findUnique({where:{organizationId_userId:{organizationId:auth.organizationId,userId:input.assignedUserId}}});if(!member||member.status!=='ACTIVE'||member.role==='VIEWER')throw new BadRequestException('Assignee is invalid.');}return this.db.conversation.update({where:{id},data:{...(input.assignedUserId!==undefined?{assignedUserId:input.assignedUserId}:{}),...(input.status!==undefined?{status:input.status}:{})}});}
  async unreadCount(auth:AuthContext){const rows=await this.list(auth,'unread');return{count:rows.data.length,capped:rows.nextCursor!==null};}
  async onModuleDestroy():Promise<void>{await this.queue.close();await this.connection.quit();}
}
