import { describe,expect,it,vi } from 'vitest';
import { ContactsController } from '../contacts/contacts.controller.js';
import { TeamsService } from '../teams/teams.service.js';
import { ConversationsService } from '../conversations/conversations.service.js';
import { MetaOAuthService } from '../integrations/meta/meta-oauth.service.js';
import { NotificationsController } from '../notifications/notifications.controller.js';
const auth={userId:'user-a',organizationId:'organization-a',sessionId:'session-a',role:'OWNER'} as const;
describe('tenant isolation contract',()=>{
 it('scopes contacts to the authenticated organization',async()=>{const findFirst=vi.fn().mockResolvedValue(null);const controller=new ContactsController({contact:{findFirst}} as never);await expect(controller.get(auth,'contact-b')).rejects.toThrow();expect(findFirst).toHaveBeenCalledWith({where:{id:'contact-b',organizationId:'organization-a'}})});
 it('scopes team users to the authenticated organization',async()=>{const findMany=vi.fn().mockResolvedValue([]);const service=new TeamsService({organizationUser:{findMany}} as never,{} as never,{} as never);await service.list(auth.organizationId);expect(findMany).toHaveBeenCalledWith(expect.objectContaining({where:{organizationId:'organization-a'}}))});
 it('scopes conversations and nested messages to the authenticated organization',async()=>{const conversationFind=vi.fn().mockResolvedValue({id:'conversation-a'});const messageFind=vi.fn().mockResolvedValue([]);const service=Object.create(ConversationsService.prototype) as ConversationsService;Object.assign(service,{db:{conversation:{findFirst:conversationFind},message:{findMany:messageFind}}});await service.messages(auth,'conversation-a');expect(conversationFind).toHaveBeenCalledWith(expect.objectContaining({where:{id:'conversation-a',organizationId:'organization-a'}}));expect(messageFind).toHaveBeenCalledWith(expect.objectContaining({where:{organizationId:'organization-a',conversationId:'conversation-a'}}))});
 it('returns only safe tenant Page fields and never credentials',async()=>{const findMany=vi.fn().mockResolvedValue([]);const service=new MetaOAuthService({metaPage:{findMany}} as never,{} as never,{} as never);await service.pages(auth.organizationId);expect(findMany).toHaveBeenCalledWith({where:{organizationId:'organization-a'},select:{id:true,externalPageId:true,name:true,status:true}});expect(JSON.stringify(findMany.mock.calls)).not.toContain('accessTokenReference')});
 it('scopes notifications to both tenant and current user',async()=>{const findMany=vi.fn().mockResolvedValue([]);const controller=new NotificationsController({notification:{findMany}} as never);await controller.list(auth);expect(findMany).toHaveBeenCalledWith(expect.objectContaining({where:{organizationId:'organization-a',userId:'user-a'}}))});
 it('limits agents to their assigned conversations',async()=>{const findFirst=vi.fn().mockResolvedValue(null);const service=Object.create(ConversationsService.prototype) as ConversationsService;Object.assign(service,{db:{conversation:{findFirst}}});await expect(service.get({...auth,userId:'agent-a',role:'AGENT'},'conversation-b')).rejects.toThrow();expect(findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'conversation-b',organizationId:'organization-a',assignedUserId:'agent-a'}}))});
 it('cannot retry a message belonging to another tenant',async()=>{const messageFind=vi.fn().mockResolvedValue(null);const service=Object.create(ConversationsService.prototype) as ConversationsService;Object.assign(service,{db:{conversation:{findFirst:vi.fn().mockResolvedValue({id:'conversation-a',channel:'MESSENGER',status:'OPEN'})},message:{findFirst:messageFind}}});await expect(service.retry(auth,'conversation-a','message-b')).rejects.toThrow();expect(messageFind).toHaveBeenCalledWith({where:{id:'message-b',conversationId:'conversation-a',organizationId:'organization-a',direction:'OUTBOUND'}})});
});
